# netlify.toml

[[headers]]
  # Set the default header to the one we want for documents
  for = "/*"
    [headers.values]
    cache-control = "public,max-age=1800"


[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=1800 "


[[redirects]]
  from = "/index.html"
  to = "/"

  [[redirects]]
  from = "/portfolio.html"
  to = "/portfolio"


  [[redirects]]
  from = "/airlie-beach-builders-logans-payground/"
  to = "/"

  [[redirects]]
  from = "/funnel-bay-lot-1-luxury-development/"
  to = "/"

  [[redirects]]
  from = "/latest-news/"
  to = "/"



